# Generated by Django 5.1.3 on 2024-11-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quality_of_life", "0002_initial"),
    ]

    operations = []
