# Generated by Django 5.1.3 on 2024-11-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_of_life", "0004_kindofappeal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalattributes",
            name="kind_of_appeal_id",
            field=models.ForeignKey(
                db_column="kind_of_appeal_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quality_of_life.kindofappeal",
            ),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="completion_date",
            field=models.DateTimeField(
                blank=True, db_column="completion_date", null=True
            ),
        ),
    ]
