# Generated by Django 5.1.3 on 2024-11-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quality_of_life",
            "0005_alter_additionalattributes_kind_of_appeal_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalattributes",
            name="budgetary_funds_are_required",
            field=models.BooleanField(
                blank=True, db_column="budgetary_funds_are_required", null=True
            ),
        ),
        migrations.AlterField(
            model_name="additionalattributes",
            name="category_id",
            field=models.IntegerField(blank=True, db_column="category_id", null=True),
        ),
        migrations.AlterField(
            model_name="additionalattributes",
            name="received_from",
            field=models.CharField(
                blank=True, db_column="received_from", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="executioninfo",
            name="call_status",
            field=models.IntegerField(blank=True, db_column="call_status", null=True),
        ),
        migrations.AlterField(
            model_name="executioninfo",
            name="current_task_id",
            field=models.IntegerField(
                blank=True, db_column="current_task_id", null=True
            ),
        ),
        migrations.AlterField(
            model_name="executioninfo",
            name="executor_id",
            field=models.IntegerField(blank=True, db_column="executor_id", null=True),
        ),
        migrations.AlterField(
            model_name="executioninfo",
            name="executor_state_institute_id",
            field=models.IntegerField(
                blank=True, db_column="executor_state_institute_id", null=True
            ),
        ),
        migrations.AlterField(
            model_name="executioninfo",
            name="executors",
            field=models.TextField(blank=True, db_column="executors", null=True),
        ),
        migrations.AlterField(
            model_name="executioninfo",
            name="process_status",
            field=models.IntegerField(
                blank=True, db_column="process_status", null=True
            ),
        ),
        migrations.AlterField(
            model_name="responseinfo",
            name="answer",
            field=models.TextField(blank=True, db_column="answer", null=True),
        ),
        migrations.AlterField(
            model_name="responseinfo",
            name="answer_quality_id",
            field=models.IntegerField(
                blank=True, db_column="answer_quality_id", null=True
            ),
        ),
        migrations.AlterField(
            model_name="responseinfo",
            name="answer_rating",
            field=models.IntegerField(blank=True, db_column="answer_rating", null=True),
        ),
        migrations.AlterField(
            model_name="responseinfo",
            name="answer_rating_from_user_id",
            field=models.IntegerField(
                blank=True, db_column="answer_rating_from_user_id", null=True
            ),
        ),
    ]
