# Generated by Django 5.1.3 on 2024-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_of_life", "0007_remove_appeal_index_right"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="boundary_coords",
            field=models.JSONField(blank=True, db_column="boundary_coords", null=True),
        ),
    ]
