# Generated by Django 5.1.3 on 2024-11-18 05:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_of_life", "0008_appeal_boundary_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="district_boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                db_column="district_boundary",
                geography=True,
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="appeal",
            name="district_name",
            field=models.TextField(blank=True, db_column="district_name", null=True),
        ),
    ]
